STYLE_LABEL_HOVER_COLOR = "#ffffff"
STYLE_LABEL_COLOR       = "#000000"
STYLE_BORDER_COLOR      = "#dcdcdc"
STYLE_SEL_BORDER_COLOR  = "#dcdcdc"
STYLE_HOVER_COLOR       = "#1a73e8"
STYLE_PRESSED_COLOR     = "#d4d4d4"
STYLE_FOCUS_COLOR       = "#d4d4d4"
STYLE_DIRTY_COLOR       = "#ff0000"
STYLE_ERR_COLOR         = "#ff0000"
STYLE_WARN_COLOR        = "#ffa000"
STYLE_ITEM_SEL_COLOR    = "#1976d2"
STYLE_ITEM_SEL_BG_COLOR = "#e3f2fd"
STYLE_ACCENT_COLOR      = "#3fb950" 
STYLE_TOOLBAR_BG_COLOR  = "#24292e"
STYLE_CONNECT_BG_COLOR  = "transparent"
STYLE_DISCONNECT_BG_COLOR  = "#ffebee"

STYLE_ERR_BADGE_BG_COLOR = "#ffebee"   
STYLE_ERR_BADGE_LABEL_COLOR = "#c62828"   


STYLE_TOOLBAR_BOLDER_COLOR    = "#000000"   
STYLE_TOOLBAR_HANDLE_COLOR    = "#8b949e"
STYLE_TOOLBAR_HOVER_COLOR     = "#14ffffff"
STYLE_TOOLBAR_DISABLE_COLOR   = "#7FFFFFFF"
STYLE_TOOLBAR_SEPARATOR_COLOR = "#444d56"

STYLE_LIST_SEL_COLOR      = "#e3f2fd"
STYLE_LIST_SEL_FONT_COLOR = "#1976d2"

STYLE_POSI_BOX_BG_COLOR      = "#f0f4f8"    
STYLE_POSI_BOX_LABEL_COLOR   = "#0d47a1"    

STYLE_PRES_BOX_BG_COLOR      = "#ffebee"    
STYLE_PRES_BOX_LABEL_COLOR   = "#c62828"    


STYLE_LABEL_BASE        = 0
STYLE_LABEL_DESCRIPTION = 1
STYLE_LABEL_TITLE       = 2
STYLE_LABEL_ICON        = 3
